### ISSUE TITLE
rotation matrix convertion to quaternion

### ISSUE THREAD

**Issue by FangGet** [KieranWynn/pyquaternion#33]
you code validate rotation matrix must be orthogonal and its determinant must be precisely 1., which is not the case for many real datset like 7scenes.

I wonder if it's possible for you to ease the limitation for this? We can set a relative big number for np.allclose and np.isclose to tolerate many datasets.

Thank you

**Comment by pabloariasal** [comment]
I'm also having problems with default thresholds for tolerance for when a matrix is considered orthogonal. Due to numeric errors I'm unable to construct many quaternions from a rotation matrix because the np.allclose tolerances are too restrictive for my use case. Relaxing them or letting the user adjust the tolerance seems like a good idea to me.

**Comment by KieranWynn** [comment]
Thanks for the feedback. A number of people have raised this, issue. 
It will be fixed in a future release, coming soon!
See https://github.com/KieranWynn/pyquaternion/pull/44

**Comment by FangGet** [comment]
Glad to hear that.
